type: google.api.Service
config_version: 3

http:
  rules:
    - selector: product.ProductService.CreateProduct
      post: "/product/create"
      body: "*"
    - selector: product.ProductService.FindOne
      get: "/product/find-one"
    - selector: product.ProductService.DecreaseStock
      post: "/product/decrease-stock"
      body: "*"