GET http://localhost:8081/auth/jwk
Content-Type: application/json

###
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "email": "sukenda@gmail.com",
  "password": "sukenda"
}

###
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "sukenda@gmail.com",
  "password": "sukenda"
}

### KRAKEND GATEWAY

GET http://localhost:8080/__health

###

POST http://localhost:8080/v1/auth/register
Content-Type: application/json

{
  "email": "soekenda09@gmail.com",
  "password": "sukenda",
  "profile": "Kenda"
}

###
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
  "email": "soekenda09@gmail.com",
  "password": "sukenda"
}

###
POST http://localhost:8080/v1/auth/validate
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsImtpZCI6ImJsdWViaXJkLmlkIn0.eyJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOiIxNjYyNTQ4OTMzIiwiaWF0IjoiMCIsImlzcyI6Imh0dHA6Ly9hdXRoLXNlcnZpY2U6ODA4MSIsImp0aSI6Im1uYjIzdmNzcnQ3NTZ5dWlvbW5idmN4OThlcnR5dWlvcCIsInJvbGVzIjpbInJvbGVfYSIsInJvbGVfYiJdLCJzdWIiOiIxMjM0NTY3ODkwcXdlcnR5dWlvIn0.FddGSbnVralNw_--0LXrlCmb2L7zOdeU6JdrYo_Gm18"
}