POST http://localhost:8083/product/create
Content-Type: application/json

{
  "name": "Mie Rebus 01",
  "price": 1000,
  "stock": 1000
}

### KRAKEND GATEWAY
POST http://localhost:8080/v1/product/create
Content-Type: application/json

{
  "name": "Mie Rebus 01",
  "price": 1000,
  "stock": 10
}
