POST http://localhost:8083/product/create
Content-Type: application/json

{
  "name": "Mie Rebus 01",
  "price": 1000,
  "stock": 100
}

### KRAKEND GATEWAY
POST http://localhost:8080/v1/product/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImJsdWViaXJkLmlkIn0.eyJhdWQiOiJodHRwOi8vYXBpLmV4YW1wbGUuY29tIiwiZXhwIjoxNzM1Njg5NjAwLCJpc3MiOiJodHRwczovL2tyYWtlbmQuaW8iLCJqdGkiOiJtbmIyM3Zjc3J0NzU2eXVpb21uYnZjeDk4ZXJ0eXVpb3AiLCJyb2xlcyI6WyJyb2xlX2EiLCJyb2xlX2IiXSwic3ViIjoiMTIzNDU2Nzg5MHF3ZXJ0eXVpbyJ9.CnERXWl6rKDEngZOlP5fRS7k_dQwzvjJ0lnf70uiXV4

{
  "name": "KRAKEND GATEWAY",
  "price": 1000,
  "stock": 100
}
